CW/CW/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('CWblog.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CW/CW2018/CW2018/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('CWcore.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CW/CW2018/CWcore/urls.py
from django.urls import path
from .import views

app_name = "CWcore"

urlpatterns = [
    path('home/', views.home, name="home"),
    path('upload/', views.uploadimg, name="uploadimg"),
    path('voice/', views.voiceblog, name="voiceblog"),
    path('vlog/', views.vlog, name="vlog"),
    path('about/', views.about, name="about"),
    path('warning/', views.uploadimg),
]

CW/CWblog/urls.py
from django.urls import path, re_path
from .views import HomeView, BlogView, GalleryView, DetailView, AboutView, Write_ArticleView, BooksView
from . import views
app_name = 'CWblog'

urlpatterns = [
    path('', HomeView.as_view(), name="home"),
    path('blog/', BlogView.as_view(), name="blog"),
    path('success/', views.userUpdate, name="userupdate"),
    path('history/', views.get_history, name="get_weather"),
    re_path(r'^detail/(?P<pk>[0-9]+)/$', DetailView.as_view(), name="detail"),
    path('gallery/', GalleryView.as_view(), name="gallery"),
    path('about/', AboutView.as_view(), name="about"),
    path('write_Article/', Write_ArticleView.as_view(), name="write_article"),
    path('booksview/', BooksView.as_view(), name="books"),
]

CW/CW2018/CWcore/models.py
from django.db import models
from ckeditor.fields import RichTextField
# Create your models here.


class Author(models.Model):
	objects = models.Manager()
	author = models.CharField(max_length=30)

	def __str__(self):
		return self.author


class Article(models.Model):
	objects = models.Manager()
	title = models.CharField(max_length=50)
	author = models.ForeignKey(Author, on_delete=models.CASCADE)
	published = models.BooleanField(default=True)
	pub_date = models.DateTimeField("date_published")
	contents = RichTextField()

	def __str__(self):
		return self.title



class UploadFile(models.Model):
	name=models.CharField(max_length=30)
	upload_items = models.FileField(upload_to='file',null=False,blank=True)
	def __unicode__(self):
		return self.name

CW/CWblog/models.py
from django.db import models
from ckeditor.fields import RichTextField
# Create your models here.


class Author(models.Model):
    objects = models.Manager()
    author = models.CharField(max_length=30)

    def __str__(self):
        return self.author


class Article(models.Model):
    objects = models.Manager()
    title = models.CharField(max_length=50)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    published = models.BooleanField(default=True)
    pub_date = models.DateTimeField("date_published")
    contents = RichTextField()

    class Meta:
        ordering = ['id']

    def __str__(self):
        return self.title


class Userupdate(models.Model):
    objects = models.Manager()
    contents = models.TextField(blank=False)

    def __str__(self):
        return self.contents


class Gallery(models.Model):
    objects = models.Manager()
    title = models.CharField(max_length=50)
    pub_date = models.DateTimeField("date_published")
    image = models.ImageField(upload_to='media/%Y/%m', verbose_name="图片名称")

    def __str__(self):
        return self.title

CW/CWblog/views.py
import json, random, requests
from django.http import JsonResponse
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.shortcuts import render, get_object_or_404
from django.views import View
# from django.core.cache import cache
# from django.views.decorators.cache import cache_page
# from django_redis import get_redis_connection
from .models import Article, Userupdate, Gallery
# conn = get_redis_connection("default")


def userUpdate(request):

    if request.method=="POST":
        context = request.POST.get("contents", "")
        value = Userupdate.objects.create(contents = context)
        value.save()
    return render(request, "CWblog/success.html")


# @cache_page(60)
class HomeView(View):

    def get(self, request):
        article = Article.objects.all()
        paginator = Paginator(article, 2)
        page = request.GET.get('page')
        contacts = paginator.get_page(page)
        if request.method == "GET":
            content = {"article" : article, "contacts": contacts}
            return render(request, "CWblog/home.html", locals())


# @cache_page(60)
class BlogView(View):

    def get(self, request):
        article = Article.objects.all()
        paginator = Paginator(article, 2)
        page = request.GET.get('page')
        contacts = paginator.get_page(page)
        if request.method == "GET":
            content = {"article" : article, "contacts": contacts}
            return render(request, "CWblog/blog.html", locals())


class DetailView(View):

    def get(self, request, pk):
        context = {}
        article = Article.objects.get(pk=pk)
        context = {
            'next_article' : Article.objects.filter(pub_date__gt=article.pub_date).first(),# 取最后一条
            'previous_article' : Article.objects.filter(pub_date__lt=article.pub_date).last(),
            'article' : article,
        }
        return render(request, "CWblog/detail.html", locals())


# @cache_page(60)
class GalleryView(View):

    def get(self, request):
        if request.method == "GET":
            imgs = Gallery.objects.all()
            content = {"imgs" : imgs}
            return render(request, "CWblog/gallery.html", content)


# @cache_page(60)
class AboutView(View):

    def get(self, request):
        return render(request, "CWblog/about.html")


# @cache_page(60)
class Write_ArticleView(View):

    def get(self, request):
        return render(request, "CWblog/write_article.html")


# @cache_page(60)
class BooksView(View):

    def get(self, request):
        r = requests.get('http://api.avatardata.cn/MingRenMingYan/LookUp?key=94c4ce1a2700451b94e54f99085ba645&keyword=天才&page=1&rows=5')
        random_num = random.randint(0, 4)
        response_dict = r.json()
        data = response_dict['result'][random_num]
        famous_name = data['famous_name']
        famous_saying = data['famous_saying']
        return render(request, 'CWblog/books.html', locals())


def get_history(self):
    r = requests.get("http://api.avatardata.cn/HistoryToday/LookUp?key=217e09fd9e374ac7a0aff058e37cb7d9&yue=1&ri=1&type=1&page=1&rows=5")
    response_dict = r.json()
    data = response_dict['result']
    return JsonResponse(data, safe=False)

CW/CW2018/CWcore/templates/CWcore/about.html
<!doctype html>
{% extends "CWcore/base.html" %}
{% load static %}
{% block 主体 %}
<div class="content"><h2>一个意图解决交流隔阂的项目。</h2></div>
{% endblock %}

CW/CW2018/CWcore/templates/CWcore/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>CommunicationsWE</title>
	<link href="{% static 'CWcore/icons/base_icon.png' %}" rel="shortcut icon" />
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0; maximum-scale=1.0; user-scalable=0;" />
	<link rel="stylesheet" href="https://unpkg.com/purecss@0.6.1/build/base-min.css">
	<link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/pure-min.css" integrity="sha384-nn4HPE8lTHyVtfCBi5yW9d20FjT8BJwUXyWZT9InLYax14RDjBj46LmSztkmNP9w" crossorigin="anonymous">
	<!--[if lte IE 8]><!-->
    	<link rel="stylesheet" href="{% static 'CWcore/css/pure-release-0.6.1/grids-responsive-old-ie-min.css' %}">
	<!--[endif]-->
	<!--[if gt IE 8]><!-->
    	<link rel="stylesheet" href="{% static 'CWcore/css/pure-release-0.6.1/grids-responsive-min.css' %}">
	<!--<![endif]-->
	<link rel="stylesheet" href="{% static 'CWcore/css/base.css' %}">
	<link rel="stylesheet" href="{% block css %}{% endblock %}">
	
</head>
<body>
	{% block 主体 %}{% endblock %}
</html>

CW/CW2018/CWcore/templates/CWcore/home.html
<!DOCTYPE html>
{% extends "CWcore/base.html" %}
{% load static %}
{% block css %}{% static 'CWcore/css/home.css' %}{% endblock %}

	{% block 主体 %}
	<div class="pure-g">
			<nav class="pure-u-1 pure-u-md-1">
					<ul class="pure-menu-horizontal pure-menu-scrollable">
						<li class="pure-menu-item"><h1 class="pure-menu-heading">CommunicationsWe</h1></li>
						<li class="pure-menu-item"><a href="{% url 'CWcore:home' %}" class="pure-menu-link">主页</a></li>
						<li class="pure-menu-item"><a href="{% url 'CWcore:voiceblog' %}" class="pure-menu-link">有声Blog</a></li>
						<li class="pure-menu-item"><a href="{% url 'CWcore:vlog' %}" class="pure-menu-link">Vlog</a></li>
						<li class="pure-menu-item"><a href="#" class="pure-menu-link">阅读分享</a></li>
						<li class="pure-menu-item"><a href="#" class="pure-menu-link">交流空间</a></li>
						<li class="pure-menu-item"><a href="{% url 'CWcore:about' %}" class="pure-menu-link">关于CommunicationsWE</a></li>
						<li class="pure-menu-item">
							<form class="pure-form">
								<input type="text" class="pure-input-rounded pure-u-1">
								<button type="submit" class="pure-button">搜索</button>
							</form>
						</li>
					</ul>
				</nav>
	<div class="pure-u-1 pure-u-md-1-3 side-menu custom-restricted-width">
		<span class="pure-menu-heading">上传你自己的生活</span>
			<ul class="pure-menu-list pure-g-1-2">
					<li class="pure-menu-item">
						<form class="pure-form" method="POST" action="{% url 'CWcore:uploadimg' %}" enctype="multipart/form-data">
							{% csrf_token %}
							<div class="pure-u-1-4">
									<a href="" class="file pure-button">选择文件<input class="change" type="file" name="items"></a>
							<br>
								<button class="pure-button pure-button-primary" type="submit" method="POST">上传</button>
							</div>
						</form>
					</li>
				<li class="pure-menu-item"><a href="#" class="pure-menu-link">Messenger</a></li>
				<li class="pure-menu-item"><a href="#" class="pure-menu-link">Sports</a></li>
				<li class="pure-menu-item"><a href="#" class="pure-menu-link">Finance</a></li>
			</ul>
	</div>
		<main class="pure-u-1 pure-u-md-1-2 text_center">
			<div class="contents pure-menu-list">
				{% if warning %}
				<div>
					<strong>{{ warning }}</strong>
				</div>
				{% endif %}
				{% for every_article in article %}
					<table class="pure-table">
						<h3>{{ every_article.title }}</h3>
						<h6>作者：{{ every_article.author }}</h6>
						<p>{{ every_article.contents | safe }}</p>
					</table>
				{% endfor %}
			</div>
		</main>

		<footer class="pure-u-1 pure-u-md-11-24 text-center">
			<div>
				<div class="row">
				<div class="col-12">
					<p>Copyright © CWker. All rights reserved.</p>
				</div>
				</div>
			</div>
		</footer>
	{% endblock %}

CW/CWblog/templates/CWblog/about.html
<!doctype html>
{% extends "CWblog/home.html" %}
{% load static %}
{% block content %}
  <main class="pure-u-1 pure-u-md-1-2 text_center">
    <div class="contents pure-u-md-1-2">
      <h2 class="title-font"><i class="fas fa-asterisk"></i>关于CommunicationsWe</h2>
      <p class="title-font">这是一个意图解决人们沟通隔阂的项目，基于Django框架及PureCSS框架进行开发。</p>
      <p class="title-font">目前主要功能有：</p>
      <ul class="title-font">
        <li>博客赏析功能</li>
        <li>上传文章功能</li>
        <li>API对接的历史上的今天功能</li>
        <li>相册欣赏功能</li>
      </ul>
    </div>
  </main>
{% endblock %}

CW/CWblog/templates/CWblog/base.html
<!DOCTYPE html>
{% load static %}
<html>
	<head>
		<meta charset="utf-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<title>CommunicationsWE</title>
		<link href="{% static 'CWblog/icons/base_icon.png' %}" rel="shortcut icon" />
		<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0; maximum-scale=1.0; user-scalable=0;" />
		<!-- pure -->
		<link rel="stylesheet" href="https://unpkg.com/purecss@0.6.1/build/base-min.css">
		<link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/pure-min.css" integrity="sha384-nn4HPE8lTHyVtfCBi5yW9d20FjT8BJwUXyWZT9InLYax14RDjBj46LmSztkmNP9w" crossorigin="anonymous">
		<!-- bootstrap
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous"> -->
		<!-- fontawesome -->
		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
		<!--[if lte IE 8]><!-->
			<link rel="stylesheet" href="{% static 'CWblog/css/pure-release-0.6.1/grids-responsive-old-ie-min.css' %}">
		<!--[endif]-->
		<!--[if gt IE 8]><!-->
			<link rel="stylesheet" href="{% static 'CWblog/css/pure-release-0.6.1/grids-responsive-min.css' %}">
		<!--<![endif]-->
		<link rel="stylesheet" href="{% static 'CWblog/css/base.css' %}">
		<link rel="stylesheet" href="{% block css %}{% endblock %}">

	</head>
	<body>
		<div id="wapper">
			{% block nav %}{% endblock %}
			{% block side_menu %}{% endblock %}
			{% block content %}{% endblock %}
			{% block side_gallery %}{% endblock %}
      {% block footer %}{% endblock %}
    </div>

	</body>
	<script type="text/javascript" src="{% static 'CWblog/js/jquery-3.3.1.js' %}"></script>
	<script type="text/javascript" src="https://unpkg.com/wangeditor@3.1.1/release/wangEditor.min.js"></script>
	<script type="text/javascript" src="{% static 'CWblog/js/wangEditor.js' %}"></script>
	<script type="text/javascript" src="{% static 'CWblog/js/get_history.js' %}"></script>
</html>

CW/CWblog/templates/CWblog/blog.html
<!DOCTYPE html>
{% extends "CWblog/home.html" %}
{% load static %}

{% block content %}
  <main class="pure-u-1-2 pure-u-md-1-2 text_center">
    <div class="contents pure-u-md-1-2">
      <nav aria-label="Page navigation example">
        {% for contact in contacts %}
        <table class="pure-table">
            <h3><a class="title-font" href="{% url 'CWblog:detail' pk=contact.pk %}"><i class="far fa-newspaper"></i>{{ contact.title }}</a></h3>
            <h6 class="title-font"><i class="far fa-edit"></i> 作者：{{ contact.author }}</h6>
            <div class="article-font">{{ contact.contents | striptags | truncatechars:120 | safe}}</div>
          </table>
        {% endfor %}
        
        <ul class="pagination">
          {% if contacts.has_previous %}
            <li class="page-item"><span class="sr-only">Previous</span>
              <a class="page-link" href="?page={{ contacts.previous_page_number }}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
              </a>
            </li>
          {% endif %}
          <li class="page-item"><a class="page-link" href="?page={{ contacts.number }}">{{ contacts.number }}</a></li>
          {% if contacts.has_next %}
            <li class="page-item"><span class="sr-only">Next</span>
              <a class="page-link" href="?page={{ contacts.next_page_number }}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
              </a>
            </li>
          {% endif %}
        </ul>
      </nav>
    </div>
  </main>
{% endblock %}


{% block side_gallery %}

<div class="pure-u-1-3 pure-u-md-2-2">
  </i><h3 class="title-font"><i class="fas fa-cannabis"></i>  历史上的今天  </h3>
  <ul id="result"></ul>
</div>
{% endblock %}

CW/CWblog/templates/CWblog/books.html
<!doctype html>
{% extends "CWblog/home.html" %}
{% load static %}

{% block content %}
  <main class="pure-u-1-3 pure-u-md-1-2 content">
    <div class="contents pure-u-md-2-5">
      <nav aria-label="Page navigation example">
        
        
      </nav>
    </div>
  </main>
{% endblock %}

{% block side_gallery %}
  <div class="pure-u-1-3 pure-u-md-2-2">
    </i><h2 class="title-font"><i class="fas fa-cannabis"></i>  名人名言  </h2>
    <div class="title-font">{{ famous_saying }} </div>
    <div class="article-font">{{ famous_name }}<div>

  </div>
{% endblock %}

CW/CWblog/templates/CWblog/detail.html
<!doctype html>
{% extends "CWblog/home.html" %}
{% load static %}


{% block content %}
  <main class="pure-u-1 pure-u-md-1-2 text_center">
    <div class="contents pure-u-md-1-1 pure-paginator">
      {% if article %}
        <table class="pure-table">
          <h3><a class="title-font" href="">{{ article.title }}</a></h3>
          <h6 class="title-font">作者：{{ article.author }}</h6>
          <div class="article-font">{{ article.contents|safe }}</div>
        </table>
        <div class="blog-more">
            <p class="article-link">上一篇：
                {% if context.previous_article %}
                <a class="article-link" href="{% url 'CWblog:detail' context.previous_article.pk %}">{{ context.previous_article.title }}</a>
                {% else %}
                    没有了
                {% endif %}
            </p>
            <p class="article-link">下一篇：
                {% if context.next_article %}
                    <a class="article-link" href="{% url 'CWblog:detail' context.next_article.pk %}">{{ context.next_article.title }}</a>
                {% else %}
                    没有了
                {% endif %}
            </p>
        </div>
      {% endif %}
    </div>
  </main>
{% endblock %}

{% block side_gallery %}{% endblock %}

CW/CWblog/templates/CWblog/gallery.html
<!doctype html>
{% extends "CWblog/home.html" %}
{% load static %}
{% block css %}{% static 'CWblog/css/gallery.css' %}{% endblock %}
{% block content %}
  <main class="pure-u-1-2 pure-u-md-1-2 main">
    <div class="contents pure-u-md-2-5">
      {% for image in imgs %}
        <div class="box">
            <img class="pic" src="{{ MEDIA_URL }}{{ image.image.url }}" />
        </div>
      {% endfor %}
    </div>
  </main>
{% endblock %}

{% block side_gallery %}{% endblock %}

CW/CWblog/templates/CWblog/home.html
<!DOCTYPE html>
{% extends "CWblog/base.html" %}
{% load static %}
{% block css %}{% static 'CWblog/css/home.css' %}{% endblock %}

{% block nav %}
  <div class="pure-g">
    <nav class="pure-u-1 pure-u-md-1">
        <ul class="pure-menu-horizontal pure-menu-scrollable">
          <li class="pure-menu-item"><h1 class="pure-menu-heading"><a class="title-font" href="{% url 'CWblog:home' %}">CommunicationsWe</a></h1></li>
          <li class="pure-menu-item"><a href="{% url 'CWblog:home' %}" class="pure-menu-link">主页</a></li>
          <li class="pure-menu-item"><a href="{% url 'CWblog:blog' %}" class="pure-menu-link">Blog</a></li>
          <li class="pure-menu-item"><a href="{% url 'CWblog:gallery' %}" class="pure-menu-link">Gallery</a></li>
          <li class="pure-menu-item"><a href="{% url 'CWblog:about' %}" class="pure-menu-link">关于CommunicationsWE</a></li>
          <li class="pure-menu-item">
          </li>
        </ul>
        <hr class="hrtest">
    </nav>
  </div>
{% endblock %}

{% block side_menu %}
  <div class="pure-u-1-5 pure-u-md-1-5 side-menu custom-restricted-width">
    <span class="pure-menu-heading title-font">记录你自己的点滴生活</span>
    <div class="pure-menu custom-restricted-width">
      <ul class="pure-menu-list pure-g-1-2">
        <hr class="hrtest">
        <li class="pure-menu-item"><a href="{% url 'CWblog:write_article' %}" class="pure-menu-link">上传文章</a></li>
        <li class="pure-menu-item"><a href="{% url 'CWblog:books' %}" class="pure-menu-link">书籍推荐</a></li>
        <li class="pure-menu-item"><a href="{% url 'CWblog:about' %}" class="pure-menu-link">关于</a></li>
      </ul>
      <hr class="hrtest">
    </div>
  </div>
{% endblock %}

{% block content %}
  <main class="pure-u-1-3 pure-u-md-1-2 content">
    <div class="contents pure-u-md-2-5">
      <nav aria-label="Page navigation example">
        </i><h2 class="title-font"><i class="fas fa-cannabis"></i>  推荐博文  </h2>
        {% for contact in contacts %}
        <table class="pure-table">
            <h3><a class="title-font" href="{% url 'CWblog:detail' pk=contact.pk %}"><i class="far fa-newspaper"></i> {{ contact.title }}</a></h3>
            <h6 class="title-font"><i class="far fa-edit"></i> 作者：{{ contact.author }}</h6>
            <div class="article-font">{{ contact.contents | striptags | truncatechars:500 | safe}}</div>
          </table>
        {% endfor %}
      </nav>
    </div>
  </main>
{% endblock %}

{% block side_gallery %}
  <div class="pure-u-1-3 pure-u-md-2-2">
    <img class="pure-u-2-2 pure-img box" src="{% static 'CWblog/images/beach.jpg' %}"/>
  </div>
{% endblock %}

{% block footer %}
  <footer class="pure-u-1 footer title-font">
    <div>
      <div class="row">
        <p>Copyright © Powered By PureCSS, Django & FontAwesome.</p>
      </div>
    </div>
  </footer>
{% endblock %}

CW/CWblog/templates/CWblog/success.html
<!doctype html>
{% extends "CWblog/home.html" %}
{% load static %}

{% block content %}
  <main class="pure-u-1 pure-u-md-1-2 text_center">
    <div class="contents pure-u-md-1">
      <h1 class="title-font">提交日记成功.</h1>
      <h1></h1>
    </div>
  </main>
{% endblock %}

{% block side_gallery %}{% endblock %}

CW/CWblog/templates/CWblog/vlog.html
<!doctype html>
{% extends "CWblog/home.html" %}
{% load static %}

CW/CWblog/templates/CWblog/voiceblog.html
<!doctype html>
{% extends "CWblog/home.html" %}
{% load static %}

CW/CWblog/templates/CWblog/write_article.html
<!doctype html>
{% extends "CWblog/home.html" %}
{% load static %}


{% block content %}
  <main class="pure-u-1 pure-u-md-1-2 text_center">
    <div class="contents pure-u-md-1">
      <form action="/success/" method="post">
        {% csrf_token %}
        <h1 class="article-font">在这里写下您的短文或感想。。。</h1>
        <div id="div1" class="toolbar"></div>
        <textarea id="text1" style="width:100%; height:200px;" class="text" name="contents"></textarea>
        <input class="pure-button" value="上传提交" type="submit">
        
      </form>
    </div>
  </main>
{% endblock %}

{% block side_gallery %}{% endblock %}